### ISSUE TITLE
Calculator appears underneath the HUD layer 

### ISSUE THREAD

**Issue by the-eric-kwok** [Skittyblock/SixLS#13]
Steps:
1. Pull up control center without unlocking your phone
2. Activate calculator or timer in control center 

Version: 1.0.4-1 on iOS 12.1 with unc0ver JB

![23F791F0-1FCB-4B6A-9A70-3FDBAF11D115](https://user-images.githubusercontent.com/16463312/57500263-6820d380-7315-11e9-89a4-40bfdf29cf66.jpeg)
![33BC08E4-B875-42D7-97DF-297CCCBF0194](https://user-images.githubusercontent.com/16463312/57500262-6820d380-7315-11e9-9334-d2112e355117.png)
![E8F54C1F-9E12-4687-9774-5E1A1300B787](https://user-images.githubusercontent.com/16463312/57500264-68b96a00-7315-11e9-8f88-3f2fd19ebf65.png)

**Comment by TheAwesome98-Real** [comment]
It doesn’t happen for me.
