### ISSUE TITLE
12h format notifications

### ISSUE THREAD

**Issue by Grafovich** [Skittyblock/SixLS#16]
I've found a small bug. I have 24H time feature enabled, but notifications still have 12H format. iP7, iOS 12.1.2. Superb tweak, i love it. Thank you!
![IMG_0151](https://user-images.githubusercontent.com/16868086/75067848-fe1d9780-54fe-11ea-992b-efed132e90a8.PNG)

**Comment by Grafovich** [comment]
This happens on iOS 13.5 too. :(
Need fix, please.

**Comment by TheAwesome98-Real** [comment]
not for me iirc

**Comment by Skittyblock** [comment]
fixed, sorry it took a year
