### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by freex818** [Skittyblock/SixLS#18]
On iOS 13.5 . Can’t select notifications from the six ls lock screen, and when you swipe to unlock and slide down for the iphones notifications . You can’t select any notifications until you close it and reopen iPhone notifications tray.

**Comment by TheAwesome98-Real** [comment]
~~Same, but only the first bit, I think I that’s getting implemented later,~~ the second bit I think is another tweak problem.

EDIT: actually it is supposed to happen. Same for me on iOS 13.5.1, but again, not the second part

**Comment by Skittyblock** [comment]
You're supposed to be able to swipe the notification icon to the side to open one

**Comment by TheAwesome98-Real** [comment]
Oh, I thought you were able to tap notifications.

**Comment by TheAwesome98-Real** [comment]
It doesn’t happen for me, let me rejail and I’ll screenrecord
