### ISSUE TITLE
[Suggestion] Touch ID unlock but you still have to slide

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Skittyblock/SixLS#19]
Touch ID unlocks the phone, maybe you could make it so it doesn’t but you can slide to open, and you don’t need to enter password?

**Comment by worf1337** [comment]
Yes I've wanted that

**Comment by Skittyblock** [comment]
If you disable the home button to unlock doesn't that do the trick? Otherwise disable the rest finger to unlock setting for Touch ID.

**Comment by TheAwesome98-Real** [comment]
> If you disable the home button to unlock doesn't that do the trick? Otherwise **disable the rest finger to unlock setting** for Touch ID.

Ah that must be it. Thanks, Skitty! :)
