### ISSUE TITLE
Slide text, power sound, home button bugs

### ISSUE THREAD

**Issue by Grafovich** [Skittyblock/SixLS#21]
After iOS 13.5 (iPhone 7, Uncover) update few more bugs revealed:
1. "Disable Home Button" doesn't work any more.
2. After respring "slide to unlock" text has a black "underlay". Back to normal after first unlock.
3. No more old "connected to power" sound.

![IMG_0137](https://user-images.githubusercontent.com/16868086/90967546-5b63c700-e4e9-11ea-8736-e5d51ec31e6b.PNG) ![IMG_0138](https://user-images.githubusercontent.com/16868086/90967605-273cd600-e4ea-11ea-88bc-2c8b1edfcbcf.PNG)

And also this little bug: https://github.com/Skittyblock/SixLS/issues/16#issue-569160319

**Comment by TheAwesome98-Real** [comment]
Happens for me too. When respringing, cancel out of passcode gets this black text. Sleep then wake your device, it is fixed.

EDIT: and I’ll close #20 since it’s the same issue

**Comment by Skittyblock** [comment]
Should all be fixed with the latest commit. The black text underlay is some sort of bug that I can't exactly figure out how to fully squash, but it should be able to fix itself now without unlocking the device.
