### ISSUE TITLE
Do you plan to make this work with iOS 14?

### ISSUE THREAD

**Issue by worf1337** [Skittyblock/SixLS#22]
Hi

I installed this on iOS 14 (after updating from iOS 13.5.1 and the tweak working fine) but now it hangs Springboard after installation 

Do you plan to fix this for iOS 14?

**Comment by Skittyblock** [comment]
Yes, iOS 14 support will be coming.

**Comment by worf1337** [comment]
Excellent. Thanks.

**Comment by TheAwesome98-Real** [comment]
Great. I recently upgraded and will be using this when the update comes out.

EDIT: I mean I’ll use it again haha, I used it before and can’t wait for the update 😁

**Comment by Skittyblock** [comment]
iOS 14 support in the latest commit. Will release on my repo as soon as testing is finished.
