### ISSUE TITLE
Soft-Locked

### ISSUE THREAD

**Issue by vsdfff** [Skittyblock/SixLS#34]
The Disable home button Function and the non-iOS 6 lockscreen bug happend making my iphone soft-locked forever the only apps that can open is a camera app only

**Comment by vsdfff** [comment]
iphone 7 plus ios 15.8 palera1n rootless

**Comment by Skittyblock** [comment]
Just a duplicate of #8. You can reboot and then jailbreak with tweak injection disabled to install, or reset settings via ssh.
