### ISSUE TITLE
Cannot unlock phone in landscape mode

### ISSUE THREAD

**Issue by harshmaniyar** [Skittyblock/SixLS#5]
I cannot unlock my iPhone X when locked in landscape mode.
While trying to swipe up and unlock doesn’t work or i don’t see a slide to unlock like in the portrait mode to unlock my phone.
Only way i can unlock the phone in landscape mode is when i have some notification on the lockscreen that i can swipe and open.

**Comment by Skittyblock** [comment]
iPhone X doesn't support landscape mode on lock screen. Sounds like a conflicting tweak.
