### ISSUE TITLE
Slow screen on time when you press power button

### ISSUE THREAD

**Issue by sag24ar** [Skittyblock/SixLS#9]
After using the tweak for a while, when you press power button the screen takes really long time to turn on. 
Respring fixes the issue, but only again for some time. 

Device : iPhone 6. iOS 12.1.1(unc0ver b50)

**Comment by Skittyblock** [comment]
Are you still experiencing this with 1.0.2?

**Comment by sag24ar** [comment]
Not anymore. The issue was resloved with 1.0.2.
